version: '2.0'

services:
    server:
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            - PORT=3000
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_URI=mongodb://db:27017
        volumes:
            - .:/server
            - /node_modulels
        ports:
            - 3000:3000
        depends_on:
            - db
    db:
        image: mongo
        restart: always
        volumes:
            - mongodbdata:/data/db
        ports:
            - 27017:27017
volumes:
    mongodbdata: